micronaut:
  application:
    name: golfingrecordApi

  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:IAmSoSecretItHurtsButINeedToBeLongerThanIWouldLike}"'